baseURL = 'https://chaoruan.xyz'

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "en"

googleAnalytics = "UA-52161528-1"

[params]
  # LoveIt 主题版本
  version = "0.2.X"
  defaultTheme = "auto"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  # images = ["/logo.png"]
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "Chaos Talk"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = false

  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    data = ""
  # Home page config
  # 主页信息设置
  [params.home]
      # amount of RSS pages
    # RSS 文章数目
    rss = 10
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = ""
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "Share my life experiences, tech insights, and random musings"

      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit = false
      # whether to show social links
      # 是否显示社交账号
      social = true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # Home page posts
    # 主页文章列表
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      # 主页每页显示文章数量
      paginate = 6

  [params.footer]
    enable = true
    # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
    custom = ''
    # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # LoveIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # LoveIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2022
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.social]
    GitHub = "rcgary"
    Linkedin = "chao-ruan"
    Twitter = "chaoruan"
    Email = "blog@chaoruan.dev"
    RSS = true # LoveIt 新增 | 0.2.0
    [params.social.Mastodon]
    # 排列图标时的权重 (权重越大, 图标的位置越靠后)
      weight = 0
    # 你的社交 ID
      id = "@chaoruan"
    # 你的社交链接的前缀
      prefix = "https://mastodon.social/"
    # 当鼠标停留在图标上时的提示内容
      title = "Mastodon"
  [params.page]
    hiddenFromHomePage = false
    fraction = true
    fontawesome = true
    rssFullText = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      HackerNews = false
    [params.page.comment]
      enable = true
      # Disqus 评论系统设置
      [params.page.comment.disqus]
        # LoveIt 新增 | 0.1.1
        enable = true
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = "chaosblog"
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = "UA-52161528-1"

[languages]
  [languages.en]
    weight = 1
    title = "Chaos Talk"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 4
    [languages.en.params.app]
      # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
      title = "Chaos Talk"
      # 是否隐藏网站图标资源链接
      noFavicon = false
      # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
      svgFavicon = ""
      # Android 浏览器主题色
      themeColor = "#ffffff"
      # Safari 图标颜色
      iconColor = "#5bbad5"
      # Windows v8-10磁贴颜色
      tileColor = "#da532c"


  [languages.zh-cn]
    weight = 2
    title = '炒碗软饭'
    description = '分享我的生活经验、技术见解以及随性的思考'
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 4
    [languages.zh-cn.params.app]
      # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
      title = "炒碗软饭"
      # 是否隐藏网站图标资源链接
      noFavicon = false
      # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
      svgFavicon = ""
      # Android 浏览器主题色
      themeColor = "#ffffff"
      # Safari 图标颜色
      iconColor = "#5bbad5"
      # Windows v8-10磁贴颜色
      tileColor = "#da532c"
    [languages.zh-cn.params.home.profile]
      subtitle = "分享我的生活经验、技术见解以及随性的思考"
    [languages.zh-cn.params.header.title]
      name = "炒碗软饭"
    [languages.zh-cn.params.page]
      rssFullText = false
    [languages.zh-cn.params.page.share]
      enable = true
      Twitter = true
      Weibo = true
    [languaes.zh-cn.params.page.comment]
      enable = true
      # Disqus 评论系统设置
      [languaes.zh-cn.params.page.comment.disqus]
        # LoveIt 新增 | 0.1.1
        enable = true
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = "chaosblog"


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark.renderer]
    # for ox-hugo https://ox-hugo.scripter.co/doc/goldmark/
    unsafe = true

[author]
  name = "Chao Ruan"
  email = "blog@chaoruan.dev"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
